default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: chronixx
  password: 2020
  database: livity

development:
  <<: *default
  database: livity

test:
  <<: *default
  database: livity

production:
  <<: *default
  database: livity